# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from ccimercuryapigatewaypostman.api_helper import APIHelper
from ccimercuryapigatewaypostman.models.user_createuserrequest import UserCreateuserrequest


class CreateuserControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(CreateuserControllerTests, cls).setUpClass()
        cls.controller = cls.client.createuser
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_user_createuser
    def test_user_createuser(self):
        # Parameters for the API call
        accept = 'application/json'
        body = APIHelper.json_deserialize('{"User_Id":"C27116","User_Samaccountname":"C27116","User_Upn":"Dee'
            'pak.Dash@cox.com","User_Displayname":"Dash, Deepak (CCI-Atlanta-CO'
            'N)","User_Name":"Dash Deepak","User_Jobtitle":"Contractor","User_M'
            'anager":"","User_Mail":"Deepak.Dash@cox.com","User_Location":"","U'
            'ser_Company":"Genpact LLC","Created_By":"C27116","User_Role":["CCI'
            '_CLD_Mercury_Administrator"]}', UserCreateuserrequest.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.user_createuser(accept, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Todo: Add description for test test_user_createuser_1
    def test_user_createuser_1(self):
        # Parameters for the API call
        accept = 'application/json'

        # Perform the API call through the SDK function
        result = self.controller.user_createuser_1(accept)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None
        expected_headers['access-control-allow-origin'] = None
        expected_headers['access-control-allow-methods'] = None
        expected_headers['access-control-allow-headers'] = None

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

