# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditLobRequest(object):

    """Implementation of the '/mrd/editLobRequest' model.

    TODO: type model description here.

    Attributes:
        lob_id (str): TODO: type description here.
        lob_name (str): TODO: type description here.
        short_name (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lob_id": 'lobId',
        "lob_name": 'lobName',
        "short_name": 'shortName',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 lob_id=None,
                 lob_name=None,
                 short_name=None,
                 last_modified_by=None):
        """Constructor for the MrdEditLobRequest class"""

        # Initialize members of the class
        self.lob_id = lob_id 
        self.lob_name = lob_name 
        self.short_name = short_name 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lob_id = dictionary.get("lobId") if dictionary.get("lobId") else None
        lob_name = dictionary.get("lobName") if dictionary.get("lobName") else None
        short_name = dictionary.get("shortName") if dictionary.get("shortName") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(lob_id,
                   lob_name,
                   short_name,
                   last_modified_by)
