# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddLanguageRequest(object):

    """Implementation of the '/mrd/addLanguageRequest' model.

    TODO: type model description here.

    Attributes:
        lang_cd (str): TODO: type description here.
        lang_first_char_code (str): TODO: type description here.
        lang_name (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lang_cd": 'langCD',
        "lang_first_char_code": 'langFirstCharCode',
        "lang_name": 'langName',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 lang_cd=None,
                 lang_first_char_code=None,
                 lang_name=None,
                 created_by=None):
        """Constructor for the MrdAddLanguageRequest class"""

        # Initialize members of the class
        self.lang_cd = lang_cd 
        self.lang_first_char_code = lang_first_char_code 
        self.lang_name = lang_name 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lang_cd = dictionary.get("langCD") if dictionary.get("langCD") else None
        lang_first_char_code = dictionary.get("langFirstCharCode") if dictionary.get("langFirstCharCode") else None
        lang_name = dictionary.get("langName") if dictionary.get("langName") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(lang_cd,
                   lang_first_char_code,
                   lang_name,
                   created_by)
