# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditLanguageRequest(object):

    """Implementation of the '/mrd/editLanguageRequest' model.

    TODO: type model description here.

    Attributes:
        lang_id (str): TODO: type description here.
        lang_name (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lang_id": 'langId',
        "lang_name": 'langName',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 lang_id=None,
                 lang_name=None,
                 last_modified_by=None):
        """Constructor for the MrdEditLanguageRequest class"""

        # Initialize members of the class
        self.lang_id = lang_id 
        self.lang_name = lang_name 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lang_id = dictionary.get("langId") if dictionary.get("langId") else None
        lang_name = dictionary.get("langName") if dictionary.get("langName") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(lang_id,
                   lang_name,
                   last_modified_by)
