# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddLgRequest(object):

    """Implementation of the '/mrd/addLgRequest' model.

    TODO: type model description here.

    Attributes:
        lg_cd (str): TODO: type description here.
        lg_name (str): TODO: type description here.
        org_id (str): TODO: type description here.
        lsg_id (str): TODO: type description here.
        coe_flag (str): TODO: type description here.
        hotel_flag (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lg_cd": 'lgCd',
        "lg_name": 'lgName',
        "org_id": 'orgId',
        "lsg_id": 'lsgId',
        "coe_flag": 'coeFlag',
        "hotel_flag": 'hotelFlag',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 lg_cd=None,
                 lg_name=None,
                 org_id=None,
                 lsg_id=None,
                 coe_flag=None,
                 hotel_flag=None,
                 created_by=None):
        """Constructor for the MrdAddLgRequest class"""

        # Initialize members of the class
        self.lg_cd = lg_cd 
        self.lg_name = lg_name 
        self.org_id = org_id 
        self.lsg_id = lsg_id 
        self.coe_flag = coe_flag 
        self.hotel_flag = hotel_flag 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lg_cd = dictionary.get("lgCd") if dictionary.get("lgCd") else None
        lg_name = dictionary.get("lgName") if dictionary.get("lgName") else None
        org_id = dictionary.get("orgId") if dictionary.get("orgId") else None
        lsg_id = dictionary.get("lsgId") if dictionary.get("lsgId") else None
        coe_flag = dictionary.get("coeFlag") if dictionary.get("coeFlag") else None
        hotel_flag = dictionary.get("hotelFlag") if dictionary.get("hotelFlag") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(lg_cd,
                   lg_name,
                   org_id,
                   lsg_id,
                   coe_flag,
                   hotel_flag,
                   created_by)
