# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditfunctionCodeRequest(object):

    """Implementation of the '/mrd/editfunctionCodeRequest' model.

    TODO: type model description here.

    Attributes:
        f_id (str): TODO: type description here.
        f_name (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "f_id": 'fId',
        "f_name": 'fName',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 f_id=None,
                 f_name=None,
                 last_modified_by=None):
        """Constructor for the MrdEditfunctionCodeRequest class"""

        # Initialize members of the class
        self.f_id = f_id 
        self.f_name = f_name 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        f_id = dictionary.get("fId") if dictionary.get("fId") else None
        f_name = dictionary.get("fName") if dictionary.get("fName") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(f_id,
                   f_name,
                   last_modified_by)
