# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddSLobRequest(object):

    """Implementation of the '/mrd/addSLobRequest' model.

    TODO: type model description here.

    Attributes:
        slob_cd (str): TODO: type description here.
        slob_name (str): TODO: type description here.
        lob_id (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "slob_cd": 'slobCd',
        "slob_name": 'slobName',
        "lob_id": 'lobId',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 slob_cd=None,
                 slob_name=None,
                 lob_id=None,
                 created_by=None):
        """Constructor for the MrdAddSLobRequest class"""

        # Initialize members of the class
        self.slob_cd = slob_cd 
        self.slob_name = slob_name 
        self.lob_id = lob_id 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        slob_cd = dictionary.get("slobCd") if dictionary.get("slobCd") else None
        slob_name = dictionary.get("slobName") if dictionary.get("slobName") else None
        lob_id = dictionary.get("lobId") if dictionary.get("lobId") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(slob_cd,
                   slob_name,
                   lob_id,
                   created_by)
