# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdGetPopupRequest(object):

    """Implementation of the '/mrd/getPopupRequest' model.

    TODO: type model description here.

    Attributes:
        q_id (str): TODO: type description here.
        org_id (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "q_id": 'qId',
        "org_id": 'orgId'
    }

    def __init__(self,
                 q_id=None,
                 org_id=None):
        """Constructor for the MrdGetPopupRequest class"""

        # Initialize members of the class
        self.q_id = q_id 
        self.org_id = org_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        q_id = dictionary.get("qId") if dictionary.get("qId") else None
        org_id = dictionary.get("orgId") if dictionary.get("orgId") else None
        # Return an object of this model
        return cls(q_id,
                   org_id)
