# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditFMRequest(object):

    """Implementation of the '/mrd/editFMRequest' model.

    TODO: type model description here.

    Attributes:
        fm_id (str): TODO: type description here.
        f_id (str): TODO: type description here.
        org_id (str): TODO: type description here.
        q_id (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.
        fg_id (str): TODO: type description here.
        sfg_id (str): TODO: type description here.
        f_desc (str): TODO: type description here.
        activeflag (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fm_id": 'fmId',
        "f_id": 'fId',
        "org_id": 'orgId',
        "q_id": 'qId',
        "last_modified_by": 'lastModifiedBy',
        "fg_id": 'fgId',
        "sfg_id": 'sfgId',
        "f_desc": 'fDesc',
        "activeflag": 'activeflag'
    }

    def __init__(self,
                 fm_id=None,
                 f_id=None,
                 org_id=None,
                 q_id=None,
                 last_modified_by=None,
                 fg_id=None,
                 sfg_id=None,
                 f_desc=None,
                 activeflag=None):
        """Constructor for the MrdEditFMRequest class"""

        # Initialize members of the class
        self.fm_id = fm_id 
        self.f_id = f_id 
        self.org_id = org_id 
        self.q_id = q_id 
        self.last_modified_by = last_modified_by 
        self.fg_id = fg_id 
        self.sfg_id = sfg_id 
        self.f_desc = f_desc 
        self.activeflag = activeflag 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        fm_id = dictionary.get("fmId") if dictionary.get("fmId") else None
        f_id = dictionary.get("fId") if dictionary.get("fId") else None
        org_id = dictionary.get("orgId") if dictionary.get("orgId") else None
        q_id = dictionary.get("qId") if dictionary.get("qId") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        fg_id = dictionary.get("fgId") if dictionary.get("fgId") else None
        sfg_id = dictionary.get("sfgId") if dictionary.get("sfgId") else None
        f_desc = dictionary.get("fDesc") if dictionary.get("fDesc") else None
        activeflag = dictionary.get("activeflag") if dictionary.get("activeflag") else None
        # Return an object of this model
        return cls(fm_id,
                   f_id,
                   org_id,
                   q_id,
                   last_modified_by,
                   fg_id,
                   sfg_id,
                   f_desc,
                   activeflag)
