# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditLsgRequest(object):

    """Implementation of the '/mrd/editLsgRequest' model.

    TODO: type model description here.

    Attributes:
        lsg_id (str): TODO: type description here.
        lsg_name (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lsg_id": 'lsgId',
        "lsg_name": 'lsgName',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 lsg_id=None,
                 lsg_name=None,
                 last_modified_by=None):
        """Constructor for the MrdEditLsgRequest class"""

        # Initialize members of the class
        self.lsg_id = lsg_id 
        self.lsg_name = lsg_name 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lsg_id = dictionary.get("lsgId") if dictionary.get("lsgId") else None
        lsg_name = dictionary.get("lsgName") if dictionary.get("lsgName") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(lsg_id,
                   lsg_name,
                   last_modified_by)
