# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditsubfunctionGroupRequest(object):

    """Implementation of the '/mrd/editsubfunctionGroupRequest' model.

    TODO: type model description here.

    Attributes:
        sfg_name (str): TODO: type description here.
        fg_id (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.
        sfg_id (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sfg_name": 'sfgName',
        "fg_id": 'fgId',
        "last_modified_by": 'lastModifiedBy',
        "sfg_id": 'sfgId'
    }

    def __init__(self,
                 sfg_name=None,
                 fg_id=None,
                 last_modified_by=None,
                 sfg_id=None):
        """Constructor for the MrdEditsubfunctionGroupRequest class"""

        # Initialize members of the class
        self.sfg_name = sfg_name 
        self.fg_id = fg_id 
        self.last_modified_by = last_modified_by 
        self.sfg_id = sfg_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        sfg_name = dictionary.get("sfgName") if dictionary.get("sfgName") else None
        fg_id = dictionary.get("fgId") if dictionary.get("fgId") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        sfg_id = dictionary.get("sfgId") if dictionary.get("sfgId") else None
        # Return an object of this model
        return cls(sfg_name,
                   fg_id,
                   last_modified_by,
                   sfg_id)
