# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddLobRequest(object):

    """Implementation of the '/mrd/addLobRequest' model.

    TODO: type model description here.

    Attributes:
        lob_cd (str): TODO: type description here.
        lob_name (str): TODO: type description here.
        short_name (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lob_cd": 'lobCd',
        "lob_name": 'lobName',
        "short_name": 'shortName',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 lob_cd=None,
                 lob_name=None,
                 short_name=None,
                 created_by=None):
        """Constructor for the MrdAddLobRequest class"""

        # Initialize members of the class
        self.lob_cd = lob_cd 
        self.lob_name = lob_name 
        self.short_name = short_name 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lob_cd = dictionary.get("lobCd") if dictionary.get("lobCd") else None
        lob_name = dictionary.get("lobName") if dictionary.get("lobName") else None
        short_name = dictionary.get("shortName") if dictionary.get("shortName") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(lob_cd,
                   lob_name,
                   short_name,
                   created_by)
