# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditstaffingGroupRequest(object):

    """Implementation of the '/mrd/editstaffingGroupRequest' model.

    TODO: type model description here.

    Attributes:
        lang_id (str): TODO: type description here.
        org_id (str): TODO: type description here.
        slob_id (str): TODO: type description here.
        sfg_id (str): TODO: type description here.
        comments (str): TODO: type description here.
        wfm_sg_id (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lang_id": 'langId',
        "org_id": 'orgId',
        "slob_id": 'slobId',
        "sfg_id": 'sfgId',
        "comments": 'comments',
        "wfm_sg_id": 'wfm_sg_id',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 lang_id=None,
                 org_id=None,
                 slob_id=None,
                 sfg_id=None,
                 comments=None,
                 wfm_sg_id=None,
                 last_modified_by=None):
        """Constructor for the MrdEditstaffingGroupRequest class"""

        # Initialize members of the class
        self.lang_id = lang_id 
        self.org_id = org_id 
        self.slob_id = slob_id 
        self.sfg_id = sfg_id 
        self.comments = comments 
        self.wfm_sg_id = wfm_sg_id 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lang_id = dictionary.get("langId") if dictionary.get("langId") else None
        org_id = dictionary.get("orgId") if dictionary.get("orgId") else None
        slob_id = dictionary.get("slobId") if dictionary.get("slobId") else None
        sfg_id = dictionary.get("sfgId") if dictionary.get("sfgId") else None
        comments = dictionary.get("comments") if dictionary.get("comments") else None
        wfm_sg_id = dictionary.get("wfm_sg_id") if dictionary.get("wfm_sg_id") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(lang_id,
                   org_id,
                   slob_id,
                   sfg_id,
                   comments,
                   wfm_sg_id,
                   last_modified_by)
