# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditSLobRequest(object):

    """Implementation of the '/mrd/editSLobRequest' model.

    TODO: type model description here.

    Attributes:
        slob_id (str): TODO: type description here.
        slob_name (str): TODO: type description here.
        lob_id (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "slob_id": 'slobId',
        "slob_name": 'slobName',
        "lob_id": 'lobId',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 slob_id=None,
                 slob_name=None,
                 lob_id=None,
                 last_modified_by=None):
        """Constructor for the MrdEditSLobRequest class"""

        # Initialize members of the class
        self.slob_id = slob_id 
        self.slob_name = slob_name 
        self.lob_id = lob_id 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        slob_id = dictionary.get("slobId") if dictionary.get("slobId") else None
        slob_name = dictionary.get("slobName") if dictionary.get("slobName") else None
        lob_id = dictionary.get("lobId") if dictionary.get("lobId") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(slob_id,
                   slob_name,
                   lob_id,
                   last_modified_by)
