# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdEditfunctionGroupRequest(object):

    """Implementation of the '/mrd/editfunctionGroupRequest' model.

    TODO: type model description here.

    Attributes:
        fg_id (str): TODO: type description here.
        fg_name (str): TODO: type description here.
        last_modified_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fg_id": 'fgId',
        "fg_name": 'fgName',
        "last_modified_by": 'lastModifiedBy'
    }

    def __init__(self,
                 fg_id=None,
                 fg_name=None,
                 last_modified_by=None):
        """Constructor for the MrdEditfunctionGroupRequest class"""

        # Initialize members of the class
        self.fg_id = fg_id 
        self.fg_name = fg_name 
        self.last_modified_by = last_modified_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        fg_id = dictionary.get("fgId") if dictionary.get("fgId") else None
        fg_name = dictionary.get("fgName") if dictionary.get("fgName") else None
        last_modified_by = dictionary.get("lastModifiedBy") if dictionary.get("lastModifiedBy") else None
        # Return an object of this model
        return cls(fg_id,
                   fg_name,
                   last_modified_by)
