# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddfunctioncoderequest(object):

    """Implementation of the '/mrd/addfunctioncoderequest' model.

    TODO: type model description here.

    Attributes:
        f_cd (str): TODO: type description here.
        f_name (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "f_cd": 'fCd',
        "f_name": 'fName',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 f_cd=None,
                 f_name=None,
                 created_by=None):
        """Constructor for the MrdAddfunctioncoderequest class"""

        # Initialize members of the class
        self.f_cd = f_cd 
        self.f_name = f_name 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        f_cd = dictionary.get("fCd") if dictionary.get("fCd") else None
        f_name = dictionary.get("fName") if dictionary.get("fName") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(f_cd,
                   f_name,
                   created_by)
