# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddLsgRequest(object):

    """Implementation of the '/mrd/addLsgRequest' model.

    TODO: type model description here.

    Attributes:
        lsg_cd (str): TODO: type description here.
        lsg_name (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lsg_cd": 'lsgCd',
        "lsg_name": 'lsgName',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 lsg_cd=None,
                 lsg_name=None,
                 created_by=None):
        """Constructor for the MrdAddLsgRequest class"""

        # Initialize members of the class
        self.lsg_cd = lsg_cd 
        self.lsg_name = lsg_name 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        lsg_cd = dictionary.get("lsgCd") if dictionary.get("lsgCd") else None
        lsg_name = dictionary.get("lsgName") if dictionary.get("lsgName") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(lsg_cd,
                   lsg_name,
                   created_by)
