# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MrdAddfunctionGroupRequest(object):

    """Implementation of the '/mrd/addfunctionGroupRequest' model.

    TODO: type model description here.

    Attributes:
        fg_name (str): TODO: type description here.
        created_by (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fg_name": 'fgName',
        "created_by": 'createdBy'
    }

    def __init__(self,
                 fg_name=None,
                 created_by=None):
        """Constructor for the MrdAddfunctionGroupRequest class"""

        # Initialize members of the class
        self.fg_name = fg_name 
        self.created_by = created_by 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        fg_name = dictionary.get("fgName") if dictionary.get("fgName") else None
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else None
        # Return an object of this model
        return cls(fg_name,
                   created_by)
