# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TemplateFilterDropDownRequest(object):

    """Implementation of the '/templateFilter/dropDownRequest' model.

    TODO: type model description here.

    Attributes:
        user_id (str): TODO: type description here.
        mtype (str): TODO: type description here.
        parent_id (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_id": 'userId',
        "mtype": 'type',
        "parent_id": 'parentId'
    }

    def __init__(self,
                 user_id=None,
                 mtype=None,
                 parent_id=None):
        """Constructor for the TemplateFilterDropDownRequest class"""

        # Initialize members of the class
        self.user_id = user_id 
        self.mtype = mtype 
        self.parent_id = parent_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        user_id = dictionary.get("userId") if dictionary.get("userId") else None
        mtype = dictionary.get("type") if dictionary.get("type") else None
        parent_id = dictionary.get("parentId") if dictionary.get("parentId") else None
        # Return an object of this model
        return cls(user_id,
                   mtype,
                   parent_id)
