# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ViewGetAllViewsRequest(object):

    """Implementation of the '/view/getAllViewsRequest' model.

    TODO: type model description here.

    Attributes:
        user_id (str): TODO: type description here.
        mtype (str): TODO: type description here.
        mobile_view (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_id": 'userId',
        "mtype": 'type',
        "mobile_view": 'mobileView'
    }

    def __init__(self,
                 user_id=None,
                 mtype=None,
                 mobile_view=None):
        """Constructor for the ViewGetAllViewsRequest class"""

        # Initialize members of the class
        self.user_id = user_id 
        self.mtype = mtype 
        self.mobile_view = mobile_view 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        user_id = dictionary.get("userId") if dictionary.get("userId") else None
        mtype = dictionary.get("type") if dictionary.get("type") else None
        mobile_view = dictionary.get("mobileView") if "mobileView" in dictionary.keys() else None
        # Return an object of this model
        return cls(user_id,
                   mtype,
                   mobile_view)
