# -*- coding: utf-8 -*-

"""
ccimercuryapigatewaypostman

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.configurations.global_configuration import GlobalConfiguration
from apimatic_core.decorators.lazy_property import LazyProperty
from ccimercuryapigatewaypostman.configuration import Configuration
from ccimercuryapigatewaypostman.controllers.base_controller import BaseController
from ccimercuryapigatewaypostman.configuration import Environment
from ccimercuryapigatewaypostman.controllers.get_stats_refresh_controller\
    import GetStatsRefreshController
from ccimercuryapigatewaypostman.controllers.getdashboardview_controller\
    import GetdashboardviewController
from ccimercuryapigatewaypostman.controllers.listallview_controller\
    import ListallviewController
from ccimercuryapigatewaypostman.controllers.mapdashboardview_controller\
    import MapdashboardviewController
from ccimercuryapigatewaypostman.controllers.creategroup_controller\
    import CreategroupController
from ccimercuryapigatewaypostman.controllers.deletegroup_controller\
    import DeletegroupController
from ccimercuryapigatewaypostman.controllers.editgroup_controller\
    import EditgroupController
from ccimercuryapigatewaypostman.controllers.getgroups_controller\
    import GetgroupsController
from ccimercuryapigatewaypostman.controllers.getusergroup_controller\
    import GetusergroupController
from ccimercuryapigatewaypostman.controllers.getviewbygroup_controller\
    import GetviewbygroupController
from ccimercuryapigatewaypostman.controllers.mapgroupview_controller\
    import MapgroupviewController
from ccimercuryapigatewaypostman.controllers.removegroupview_controller\
    import RemovegroupviewController
from ccimercuryapigatewaypostman.controllers.get_moa_controller\
    import GetMoaController
from ccimercuryapigatewaypostman.controllers.get_moa_agent_controller\
    import GetMoaAgentController
from ccimercuryapigatewaypostman.controllers.get_resitech_controller\
    import GetResitechController
from ccimercuryapigatewaypostman.controllers.get_view_meta_controller\
    import GetViewMetaController
from ccimercuryapigatewaypostman.controllers.add_language_controller\
    import AddLanguageController
from ccimercuryapigatewaypostman.controllers.add_lg_controller\
    import AddLgController
from ccimercuryapigatewaypostman.controllers.add_lob_controller\
    import AddLobController
from ccimercuryapigatewaypostman.controllers.add_lsg_controller\
    import AddLsgController
from ccimercuryapigatewaypostman.controllers.add_s_lob_controller\
    import AddSLobController
from ccimercuryapigatewaypostman.controllers.addfunction_group_controller\
    import AddfunctionGroupController
from ccimercuryapigatewaypostman.controllers.addfunctioncode_controller\
    import AddfunctioncodeController
from ccimercuryapigatewaypostman.controllers.addlocation_controller\
    import AddlocationController
from ccimercuryapigatewaypostman.controllers.addorganization_controller\
    import AddorganizationController
from ccimercuryapigatewaypostman.controllers.addsubfunction_group_controller\
    import AddsubfunctionGroupController
from ccimercuryapigatewaypostman.controllers.edit_fm_controller\
    import EditFMController
from ccimercuryapigatewaypostman.controllers.edit_language_controller\
    import EditLanguageController
from ccimercuryapigatewaypostman.controllers.edit_lg_controller\
    import EditLgController
from ccimercuryapigatewaypostman.controllers.edit_lob_controller\
    import EditLobController
from ccimercuryapigatewaypostman.controllers.edit_lsg_controller\
    import EditLsgController
from ccimercuryapigatewaypostman.controllers.edit_s_lob_controller\
    import EditSLobController
from ccimercuryapigatewaypostman.controllers.editforecasted_group_controller\
    import EditforecastedGroupController
from ccimercuryapigatewaypostman.controllers.editfunction_code_controller\
    import EditfunctionCodeController
from ccimercuryapigatewaypostman.controllers.editfunction_group_controller\
    import EditfunctionGroupController
from ccimercuryapigatewaypostman.controllers.editfunction_mapping_controller\
    import EditfunctionMappingController
from ccimercuryapigatewaypostman.controllers.editlocation_controller\
    import EditlocationController
from ccimercuryapigatewaypostman.controllers.editmercurylite_controller\
    import EditmercuryliteController
from ccimercuryapigatewaypostman.controllers.editorganization_controller\
    import EditorganizationController
from ccimercuryapigatewaypostman.controllers.editstaffing_group_controller\
    import EditstaffingGroupController
from ccimercuryapigatewaypostman.controllers.editsubfunction_group_controller\
    import EditsubfunctionGroupController
from ccimercuryapigatewaypostman.controllers.get_language_controller\
    import GetLanguageController
from ccimercuryapigatewaypostman.controllers.get_master_reference_data_controller\
    import GetMasterReferenceDataController
from ccimercuryapigatewaypostman.controllers.get_mercurylite_controller\
    import GetMercuryliteController
from ccimercuryapigatewaypostman.controllers.get_popup_controller\
    import GetPopupController
from ccimercuryapigatewaypostman.controllers.getlocation_controller\
    import GetlocationController
from ccimercuryapigatewaypostman.controllers.get_fm_controller\
    import GetFMController
from ccimercuryapigatewaypostman.controllers.add_template_controller\
    import AddTemplateController
from ccimercuryapigatewaypostman.controllers.del_template_controller\
    import DelTemplateController
from ccimercuryapigatewaypostman.controllers.drop_down_controller\
    import DropDownController
from ccimercuryapigatewaypostman.controllers.edit_template_controller\
    import EditTemplateController
from ccimercuryapigatewaypostman.controllers.get_template_controller\
    import GetTemplateController
from ccimercuryapigatewaypostman.controllers.getby_id_controller\
    import GetbyIdController
from ccimercuryapigatewaypostman.controllers.checkusergroup_controller\
    import CheckusergroupController
from ccimercuryapigatewaypostman.controllers.createuser_controller\
    import CreateuserController
from ccimercuryapigatewaypostman.controllers.edituser_controller\
    import EdituserController
from ccimercuryapigatewaypostman.controllers.getusers_controller\
    import GetusersController
from ccimercuryapigatewaypostman.controllers.my_permissions_controller\
    import MyPermissionsController
from ccimercuryapigatewaypostman.controllers.updatelastlogindate_controller\
    import UpdatelastlogindateController
from ccimercuryapigatewaypostman.controllers.getuserbygroup_controller\
    import GetuserbygroupController
from ccimercuryapigatewaypostman.controllers.mapgroupuser_controller\
    import MapgroupuserController
from ccimercuryapigatewaypostman.controllers.mapusergroup_controller\
    import MapusergroupController
from ccimercuryapigatewaypostman.controllers.removeusergroup_controller\
    import RemoveusergroupController
from ccimercuryapigatewaypostman.controllers.get_u_setting_controller\
    import GetUSettingController
from ccimercuryapigatewaypostman.controllers.set_u_settings_controller\
    import SetUSettingsController
from ccimercuryapigatewaypostman.controllers.add_view_controller\
    import AddViewController
from ccimercuryapigatewaypostman.controllers.delete_views_controller\
    import DeleteViewsController
from ccimercuryapigatewaypostman.controllers.generate_view_controller\
    import GenerateViewController
from ccimercuryapigatewaypostman.controllers.get_agent_details_by_coe_controller\
    import GetAgentDetailsByCOEController
from ccimercuryapigatewaypostman.controllers.get_all_views_controller\
    import GetAllViewsController
from ccimercuryapigatewaypostman.controllers.get_data_controller\
    import GetDataController
from ccimercuryapigatewaypostman.controllers.get_half_hour_child_detail_controller\
    import GetHalfHourChildDetailController
from ccimercuryapigatewaypostman.controllers.get_view_controller\
    import GetViewController
from ccimercuryapigatewaypostman.controllers.setviewdefault_controller\
    import SetviewdefaultController
from ccimercuryapigatewaypostman.controllers.setviewfavorite_controller\
    import SetviewfavoriteController
from ccimercuryapigatewaypostman.controllers.shareview_controller\
    import ShareviewController
from ccimercuryapigatewaypostman.controllers.shareviewlogs_controller\
    import ShareviewlogsController
from ccimercuryapigatewaypostman.controllers.toggle_change_controller\
    import ToggleChangeController
from ccimercuryapigatewaypostman.controllers.viewconfig_controller\
    import ViewconfigController


class CcimercuryapigatewaypostmanClient(object):

    @LazyProperty
    def get_stats_refresh(self):
        return GetStatsRefreshController(self.global_configuration)

    @LazyProperty
    def getdashboardview(self):
        return GetdashboardviewController(self.global_configuration)

    @LazyProperty
    def listallview(self):
        return ListallviewController(self.global_configuration)

    @LazyProperty
    def mapdashboardview(self):
        return MapdashboardviewController(self.global_configuration)

    @LazyProperty
    def creategroup(self):
        return CreategroupController(self.global_configuration)

    @LazyProperty
    def deletegroup(self):
        return DeletegroupController(self.global_configuration)

    @LazyProperty
    def editgroup(self):
        return EditgroupController(self.global_configuration)

    @LazyProperty
    def getgroups(self):
        return GetgroupsController(self.global_configuration)

    @LazyProperty
    def getusergroup(self):
        return GetusergroupController(self.global_configuration)

    @LazyProperty
    def getviewbygroup(self):
        return GetviewbygroupController(self.global_configuration)

    @LazyProperty
    def mapgroupview(self):
        return MapgroupviewController(self.global_configuration)

    @LazyProperty
    def removegroupview(self):
        return RemovegroupviewController(self.global_configuration)

    @LazyProperty
    def get_moa(self):
        return GetMoaController(self.global_configuration)

    @LazyProperty
    def get_moa_agent(self):
        return GetMoaAgentController(self.global_configuration)

    @LazyProperty
    def get_resitech(self):
        return GetResitechController(self.global_configuration)

    @LazyProperty
    def get_view_meta(self):
        return GetViewMetaController(self.global_configuration)

    @LazyProperty
    def add_language(self):
        return AddLanguageController(self.global_configuration)

    @LazyProperty
    def add_lg(self):
        return AddLgController(self.global_configuration)

    @LazyProperty
    def add_lob(self):
        return AddLobController(self.global_configuration)

    @LazyProperty
    def add_lsg(self):
        return AddLsgController(self.global_configuration)

    @LazyProperty
    def add_s_lob(self):
        return AddSLobController(self.global_configuration)

    @LazyProperty
    def addfunction_group(self):
        return AddfunctionGroupController(self.global_configuration)

    @LazyProperty
    def addfunctioncode(self):
        return AddfunctioncodeController(self.global_configuration)

    @LazyProperty
    def addlocation(self):
        return AddlocationController(self.global_configuration)

    @LazyProperty
    def addorganization(self):
        return AddorganizationController(self.global_configuration)

    @LazyProperty
    def addsubfunction_group(self):
        return AddsubfunctionGroupController(self.global_configuration)

    @LazyProperty
    def edit_fm(self):
        return EditFMController(self.global_configuration)

    @LazyProperty
    def edit_language(self):
        return EditLanguageController(self.global_configuration)

    @LazyProperty
    def edit_lg(self):
        return EditLgController(self.global_configuration)

    @LazyProperty
    def edit_lob(self):
        return EditLobController(self.global_configuration)

    @LazyProperty
    def edit_lsg(self):
        return EditLsgController(self.global_configuration)

    @LazyProperty
    def edit_s_lob(self):
        return EditSLobController(self.global_configuration)

    @LazyProperty
    def editforecasted_group(self):
        return EditforecastedGroupController(self.global_configuration)

    @LazyProperty
    def editfunction_code(self):
        return EditfunctionCodeController(self.global_configuration)

    @LazyProperty
    def editfunction_group(self):
        return EditfunctionGroupController(self.global_configuration)

    @LazyProperty
    def editfunction_mapping(self):
        return EditfunctionMappingController(self.global_configuration)

    @LazyProperty
    def editlocation(self):
        return EditlocationController(self.global_configuration)

    @LazyProperty
    def editmercurylite(self):
        return EditmercuryliteController(self.global_configuration)

    @LazyProperty
    def editorganization(self):
        return EditorganizationController(self.global_configuration)

    @LazyProperty
    def editstaffing_group(self):
        return EditstaffingGroupController(self.global_configuration)

    @LazyProperty
    def editsubfunction_group(self):
        return EditsubfunctionGroupController(self.global_configuration)

    @LazyProperty
    def get_language(self):
        return GetLanguageController(self.global_configuration)

    @LazyProperty
    def get_master_reference_data(self):
        return GetMasterReferenceDataController(self.global_configuration)

    @LazyProperty
    def get_mercurylite(self):
        return GetMercuryliteController(self.global_configuration)

    @LazyProperty
    def get_popup(self):
        return GetPopupController(self.global_configuration)

    @LazyProperty
    def getlocation(self):
        return GetlocationController(self.global_configuration)

    @LazyProperty
    def get_fm(self):
        return GetFMController(self.global_configuration)

    @LazyProperty
    def add_template(self):
        return AddTemplateController(self.global_configuration)

    @LazyProperty
    def del_template(self):
        return DelTemplateController(self.global_configuration)

    @LazyProperty
    def drop_down(self):
        return DropDownController(self.global_configuration)

    @LazyProperty
    def edit_template(self):
        return EditTemplateController(self.global_configuration)

    @LazyProperty
    def get_template(self):
        return GetTemplateController(self.global_configuration)

    @LazyProperty
    def getby_id(self):
        return GetbyIdController(self.global_configuration)

    @LazyProperty
    def checkusergroup(self):
        return CheckusergroupController(self.global_configuration)

    @LazyProperty
    def createuser(self):
        return CreateuserController(self.global_configuration)

    @LazyProperty
    def edituser(self):
        return EdituserController(self.global_configuration)

    @LazyProperty
    def getusers(self):
        return GetusersController(self.global_configuration)

    @LazyProperty
    def my_permissions(self):
        return MyPermissionsController(self.global_configuration)

    @LazyProperty
    def updatelastlogindate(self):
        return UpdatelastlogindateController(self.global_configuration)

    @LazyProperty
    def getuserbygroup(self):
        return GetuserbygroupController(self.global_configuration)

    @LazyProperty
    def mapgroupuser(self):
        return MapgroupuserController(self.global_configuration)

    @LazyProperty
    def mapusergroup(self):
        return MapusergroupController(self.global_configuration)

    @LazyProperty
    def removeusergroup(self):
        return RemoveusergroupController(self.global_configuration)

    @LazyProperty
    def get_u_setting(self):
        return GetUSettingController(self.global_configuration)

    @LazyProperty
    def set_u_settings(self):
        return SetUSettingsController(self.global_configuration)

    @LazyProperty
    def add_view(self):
        return AddViewController(self.global_configuration)

    @LazyProperty
    def delete_views(self):
        return DeleteViewsController(self.global_configuration)

    @LazyProperty
    def generate_view(self):
        return GenerateViewController(self.global_configuration)

    @LazyProperty
    def get_agent_details_by_coe(self):
        return GetAgentDetailsByCOEController(self.global_configuration)

    @LazyProperty
    def get_all_views(self):
        return GetAllViewsController(self.global_configuration)

    @LazyProperty
    def get_data(self):
        return GetDataController(self.global_configuration)

    @LazyProperty
    def get_half_hour_child_detail(self):
        return GetHalfHourChildDetailController(self.global_configuration)

    @LazyProperty
    def get_view(self):
        return GetViewController(self.global_configuration)

    @LazyProperty
    def setviewdefault(self):
        return SetviewdefaultController(self.global_configuration)

    @LazyProperty
    def setviewfavorite(self):
        return SetviewfavoriteController(self.global_configuration)

    @LazyProperty
    def shareview(self):
        return ShareviewController(self.global_configuration)

    @LazyProperty
    def shareviewlogs(self):
        return ShareviewlogsController(self.global_configuration)

    @LazyProperty
    def toggle_change(self):
        return ToggleChangeController(self.global_configuration)

    @LazyProperty
    def viewconfig(self):
        return ViewconfigController(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION, config=None):
        if config is None:
            self.config = Configuration(
                                         http_client_instance=http_client_instance,
                                         override_http_client_configuration=override_http_client_configuration,
                                         http_call_back=http_call_back,
                                         timeout=timeout,
                                         max_retries=max_retries,
                                         backoff_factor=backoff_factor,
                                         retry_statuses=retry_statuses,
                                         retry_methods=retry_methods,
                                         environment=environment)
        else:
            self.config = config

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseController.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseController.user_agent(), BaseController.user_agent_parameters())

